-- create database
CREATE DATABASE IF NOT EXISTS senadmin;
-- switch to this database
\c senadmin;

-- create tables
-- cascade allows subsequent dropping on tables with master dependencies

-- TODO: rename column names to match .xlsx file for ETL convenience

DROP TABLE IF EXISTS char CASCADE;
CREATE TABLE char
(
    char_id             integer GENERATED ALWAYS AS IDENTITY,
    -- char_code           varchar UNIQUE, 37ads appears twice, maybe delete from excel and come back
    char_code           varchar NOT NULL, --temporary fix for UNIQUE declaration issues
    Title               varchar NOT NULL,
    Type                varchar NOT NULL,
    Type_Description    varchar NOT NULL,
    Web_Valid           varchar NOT NULL,
    png_file            varchar NOT NULL,
    Bullet_file         varchar NOT NULL,
    PRIMARY KEY (char_id)
);
-- DROP INDEX if EXISTS char_key;
-- CREATE UNIQUE INDEX char_key ON char (char_code);
copy char (char_code, Title, Type, Type_Description, Web_Valid, png_file, Bullet_file) from 'D:\DATA\Sensor\webApp\char.csv'  delimiter ',' csv header;
-- D:\DATA\Sensor\webApp

-- -- characteristics
-- -- DROP TABLE IF EXISTS characteristics CASCADE;
-- -- CREATE TABLE characteristics (
-- --  characteristic_id int PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
-- --  char_name              varchar(50) NOT NULL,
-- --  char_value             numeric(5,2)
-- -- );
-- DROP TABLE IF EXISTS characteristics CASCADE;
-- CREATE TABLE characteristics (
--  characteristic_id int PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
--  product_id              integer GENERATED BY DEFAULT AS IDENTITY,
--  name             varchar(50) NOT NULL
-- );
-- DROP INDEX if EXISTS char_key;
-- CREATE INDEX char_key ON characteristics (product_id);
-- copy characteristics from '/Users/jverploeg/Desktop/data/characteristics.csv'  delimiter ',' csv header;